#имя - любое
name: Demo Workflow
#событие - запуск вручную
on: workflow_dispatch
jobs: 
#имя jobs
  print:
  #с какой ОС необходимо запустить workflow -  Где должна выполняться джоба
    runs-on: windows-latest
    # Перечень шагов, которые необходимо выполнить в рамках джобы
    steps: 
        # Ключевое слово uses используется для запуска заранее созданного набора команд. В данном случае используем дефолтную команду для обновления проекта до последнего коммита.
      -  uses: actions/checkout@v3
      
    # Название шага (чтобы понимать, что выполняется на этом шаге)
      - name: Print to console    
      #Запуск
        run: echo Hello, Nastya!
